number = int(input("Enter an integer: "))
print(f"Is {number} divisible by 5 and 6?", end=" ")
print('true' if number % 5 == 0 and number % 6 == 0 else 'false')
print(f"Is {number} divisible by 5 or 6?", end=" ")
print('true' if number % 5 == 0 or number % 6 == 0 else 'false')
print(f"Is {number} divisible by 5 or 6, but not both?", end=" ")
print('true' if number % 5 == 0 and number % 6 != 0 or number % 5 != 0 and number % 6 == 0 else 'false')	